-- MySQL Script generated by MySQL Workbench
-- mar. 09 févr. 2021 12:04:02 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vaccine` DEFAULT CHARACTER SET utf8 ;
USE `db_vaccine` ;

-- -----------------------------------------------------
-- Table `db_vaccine`.`Laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vaccine`.`Laboratory` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vaccine`.`vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vaccine`.`Vaccine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sideEffects` VARCHAR(45) NULL,
  `laboratoryId` INT NULL,
  `releaseDate` DATETIME NULL,
  `typeOfVaccine` VARCHAR(45) NULL DEFAULT '',
  `injection` INT NULL,
  `StepValidation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaccine_laboratoryIdx` (`laboratoryId` ASC),
  CONSTRAINT `fk_vaccine_Laboratory`
    FOREIGN KEY (`laboratoryId`)
    REFERENCES `db_vaccine`.`Laboratory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
