version: '3.5'

services:
  db:
    build:
      context: ./
      dockerfile: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - bridge
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
     - ${PWD}/db:/var/lib/mysql

networks:
  bridge:
    driver: bridge