name: Deploy
on: 
  push:
    branches:
      - feature/add-deploy
      - dev
      - feature/improvement-deploy-ci/cd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: /home/john/node-grp4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CLONE_DIR
          port: 22
          script: |
            echo "Hello world $CLONE_DIR"
            echo git@github.com:${{github.repository}}.git
            rm -rf $CLONE_DIR
            git clone -b feature/improvement-deploy-ci/cd git@github.com:${{github.repository}}.git $CLONE_DIR
            cd $CLONE_DIR
            sed -i 's/web_port/${{ secrets.WEB_PORT }}/g' exemple.env
            cp exemple.env prod.env
            npm install
            npm run build
            ls . | grep -v "dist" | xargs rm -r