name: Test
on:
  push:
    branches:
      - dev
      - feature/integration-database-test-with-ci
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.5.8-focal
        env:
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Exec database structure and dataset.
        run: bash sql/test.sh
      - run: npm install
      - run: npm test